- name: Copy app tar file to server
  copy:
    src: app.tar.gz
    dest: /tmp/app.tar.gz

- name: Extract app
  unarchive:
    src: /tmp/app.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Set correct permissions
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'